#
###################################
# Site wide configuration
####################################
#
title: Peijie Hu
email: peijie@peijiehu.com
description: A programmer's blog on coding excercises and software development, edited by Peijie Hu.
url: https://peijiehu.github.io/code # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Los_Angeles
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

# More options - https://kramdown.gettalong.org/converter/html.html
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Peijie
  avatar: zenyatta-avatar-2.png
  job: "Programmer"
  bio: "does something."
  email: #email
  disqus-shortname: #username
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-106125145-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: peijiehu
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
